# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satti', '0002_auto_20161104_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chatrooms',
            field=models.ManyToManyField(blank=True, to='satti.ChatRoom'),
        ),
    ]
