# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satti', '0003_auto_20161104_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='messages',
            field=models.ManyToManyField(blank=True, to='satti.Message'),
        ),
    ]
