# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satti', '0004_auto_20161107_1958'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='ChatMessage',
        ),
    ]
