# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('satti', '0005_auto_20161107_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='time',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
