# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 09:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('satti', '0006_auto_20161108_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='chatrooms',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='satti.ChatUser'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='users',
            field=models.ManyToManyField(to='satti.ChatUser'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='chatuser',
            name='chatrooms',
            field=models.ManyToManyField(blank=True, to='satti.ChatRoom'),
        ),
        migrations.AddField(
            model_name='chatuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
