# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satti', '0007_auto_20161109_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='messages',
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='max_users',
            field=models.PositiveSmallIntegerField(default=50),
        ),
    ]
