# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satti', '0008_auto_20161109_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(default='static/images/default.jpg', upload_to='static/images/'),
        ),
    ]
