# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satti', '0009_auto_20161117_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatuser',
            name='picture',
        ),
        migrations.AddField(
            model_name='chatuser',
            name='image',
            field=models.ImageField(default='static/images/default.jpg', upload_to='static/images/'),
        ),
    ]
