# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satti', '0014_auto_20161117_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='picture',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='image',
            field=models.ImageField(default='/static/default.jpg', upload_to='/static/images/'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='image',
            field=models.ImageField(default='/static/default.jpg', upload_to='/static/images/'),
        ),
    ]
