# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('satti', '0021_auto_20161214_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='admins',
            field=models.ManyToManyField(related_name='admin_in', to='satti.ChatUser'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_rooms', to='satti.ChatUser'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='users',
            field=models.ManyToManyField(related_name='user_in', to='satti.ChatUser'),
        ),
    ]
