# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satti', '0022_auto_20161214_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='description',
            field=models.TextField(blank=True, default="This is the default chatroom description. It is a bit longer than the default text for profiles, and that's intentional.", max_length=200),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
