# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satti', '0023_auto_20161216_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
