# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satti', '0024_auto_20161216_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_private', models.BooleanField(verbose_name=True)),
                ('users', models.ManyToManyField(related_name='private_chats', to='satti.ChatUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='chatroom',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
