# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satti', '0026_chatuser_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatechat',
            name='users',
        ),
        migrations.DeleteModel(
            name='PrivateChat',
        ),
    ]
