# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satti', '0027_auto_20161221_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='users_online',
            field=models.ManyToManyField(to='satti.ChatUser'),
        ),
    ]
