# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('satti', '0028_chatroom_users_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='last_seen',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatuser',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
