# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satti', '0030_chatroom_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='notification',
            field=models.BooleanField(default=False),
        ),
    ]
