# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('satti', '0031_chatmessage_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='satti.ChatUser'),
        ),
    ]
