# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-30 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satti', '0034_auto_20161229_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='read_by',
            field=models.ManyToManyField(related_name='has_read', to='satti.ChatUser'),
        ),
    ]
