# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('satti', '0035_chatmessage_read_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
