# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satti', '0036_chatroom_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='modified',
            field=models.DateTimeField(),
        ),
    ]
